# ***K Means Clustering***

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Importing Training Data 
TrainingData = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/emnist-letters-train.csv")
TrainingData

23  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.406  0.407  \
0       7  0    0    0    0    0    0    0    0    0  ...      0      0   
1      16  0    0    0    0    0    0    0    0    0  ...      0      0   
2      15  0    0    0    0    0    0    0    0    0  ...      0      0   
3      23  0    0    0    0    0    0    0    0    0  ...      0      0   
4      17  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
88794   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88795  21  0    0    0    0    0    0    0    0    0  ...      0      0   
88796   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88797  23  0    0    0    0    0    0    0    0    0  ...      0      0   
88798  12  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.408  0.409  0.410  0.411  0.412  0.413  0.414  0.415  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
88794      0      0      0      0      0      0      0      0  
88795      0      0      0      0      0      0      0      0  
88796      0      0      0      0      0      0      0      0  
88797      0      0      0      0      0      0      0      0  
88798      0      0      0      0      0      0      0      0  

[88799 rows x 785 columns]

In [3]:
# Initializing X (Feature Values)
X_Table = TrainingData.drop('23', axis=1)
print('X_Table Shape : ', X_Table.shape)
print(X_Table)

X = np.array(X_Table)
print('X Shape : ', X.shape)
print(X)

X_Table Shape :  (88799, 784)
       0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.406  0.407  \
0      0    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      0    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      0    0    0    0    0    0    0    0    0    0  ...      0      0   
...   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
88794  0    0    0    0    0    0    0    0    0    0  ...      0      0   
88795  0    0    0    0    0    0    0    0    0    0  ...      0      0   
88796  0    0    0    0    0    0    0    0    0    0  ...      0      0   
88797  0    0    0    0    0    0    0    0    0    0  ...      0      0   
88798  0    0    0    0    0    0    0    0    0    0  ...      0      0   

       0.408  0.409  0.410  0.411  0.412  0.413  0.414  0

In [4]:
# Initializing Y (Labels)
Y_Table = TrainingData['23']
print('Y_Table Shape : ', Y_Table.shape)
print(Y_Table)

Y = np.array([Y_Table]).T
print('Y Shape : ', Y.shape)
print(Y)

Y_Table Shape :  (88799,)
0         7
1        16
2        15
3        23
4        17
         ..
88794     1
88795    21
88796     1
88797    23
88798    12
Name: 23, Length: 88799, dtype: int64
Y Shape :  (88799, 1)
[[ 7]
 [16]
 [15]
 ...
 [ 1]
 [23]
 [12]]


In [5]:
# Randomly Choosing Centroids
K = 26
Centroids_Table = X_Table.sample(n=K)
Centroids = np.array(Centroids_Table)
print('Centroids Shape : ', Centroids.shape)
print(Centroids)

Centroids Shape :  (26, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# Main
Iterations = 500
z=0
while(z < Iterations):
  Distances = np.zeros((X.shape[0], 26))
  for i in range(26):
    Distances[:,i] = np.array(np.sqrt(np.sum((X - Centroids[i])**2, axis=1)))

  Min = np.array([np.min(Distances, axis=1)]).T

  HotOne = (Distances == Min).astype(int)
  
  for i in range(26):
    HotOne[:,i]*=(i+1)
  Cluster = np.sum(HotOne, axis=1)

  X_Table['Cluster'] = Cluster
  Centroids_New_Table = X_Table.groupby(['Cluster']).mean()
  Centroids_New = np.array(Centroids_New_Table)
  X_Table.pop('Cluster')

  if(np.sum((Centroids_New - Centroids)**2) == 0):
    break

  Centroids_Table = Centroids_New_Table
  Centroids = Centroids_New
  z+=1

Y_Predicted = Cluster

In [7]:
# Output
print('EXPECTED vs PREDICTED')
print(np.concatenate((Y, np.array([Y_Predicted]).T), axis=1))

EXPECTED vs PREDICTED
[[ 7  5]
 [16 23]
 [15 14]
 ...
 [ 1 10]
 [23 25]
 [12  7]]


In [15]:
temp = (Y == 10).astype(int).T

a = temp*Y_Predicted
a = a[a!=0]
count = np.zeros(26)
for i in a:
  count[i-1]+=1

for i in range(1,27):
  print(i, '\t', count[i-1])

# Cluster Number may be different but the data is getting grouped into 26 different groups and Algorithm is working fine, i.e., Updating Centroids and Clustering Data into 26 different groups

1 	 3.0
2 	 2.0
3 	 783.0
4 	 14.0
5 	 8.0
6 	 3.0
7 	 285.0
8 	 7.0
9 	 109.0
10 	 22.0
11 	 192.0
12 	 233.0
13 	 27.0
14 	 7.0
15 	 29.0
16 	 0.0
17 	 71.0
18 	 7.0
19 	 178.0
20 	 8.0
21 	 1336.0
22 	 6.0
23 	 12.0
24 	 13.0
25 	 23.0
26 	 24.0
