# ***K Nearest Neighbour***

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Importing Training Data 
TrainingData = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/emnist-letters-train.csv")
TrainingData

23  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.406  0.407  \
0       7  0    0    0    0    0    0    0    0    0  ...      0      0   
1      16  0    0    0    0    0    0    0    0    0  ...      0      0   
2      15  0    0    0    0    0    0    0    0    0  ...      0      0   
3      23  0    0    0    0    0    0    0    0    0  ...      0      0   
4      17  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
88794   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88795  21  0    0    0    0    0    0    0    0    0  ...      0      0   
88796   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88797  23  0    0    0    0    0    0    0    0    0  ...      0      0   
88798  12  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.408  0.409  0.410  0.411  0.412  0.413  0.414  0.415  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
88794      0      0      0      0      0      0      0      0  
88795      0      0      0      0      0      0      0      0  
88796      0      0      0      0      0      0      0      0  
88797      0      0      0      0      0      0      0      0  
88798      0      0      0      0      0      0      0      0  

[88799 rows x 785 columns]

In [3]:
# Initializing X (Feature Values) for training
X = np.array(TrainingData.drop('23', axis=1))

print(X.shape)
print(X)

(88799, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
# Importing Testing Data 
TestingData = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/emnist-letters-test.csv")
TestingData

1  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.548  0.549  \
0       1  0    0    0    0    0    0    0    0    0  ...      0      0   
1       1  0    0    0    0    0    0    0    0    0  ...      0      0   
2       1  0    0    0    0    0    0    0    0    0  ...      0      0   
3       1  0    0    0    0    0    0    0    0    0  ...      0      0   
4       1  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
14794  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14795  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14796  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14797  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14798  19  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.550  0.551  0.552  0.553  0.554  0.555  0.556  0.557  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
14794      0      0      0      0      0      0      0      0  
14795      0      0      0      0      0      0      0      0  
14796      0      0      0      0      0      0      0      0  
14797      0      0      0      0      0      0      0      0  
14798      0      0      0      0      0      0      0      0  

[14799 rows x 785 columns]

In [5]:
# Initializing Y (Labels) for testing
Y = np.array([TestingData['1']]).T

print('Y Shape : ', Y.shape)
print(Y)

Y Shape :  (14799, 1)
[[ 1]
 [ 1]
 [ 1]
 ...
 [19]
 [19]
 [19]]


In [6]:
# Initialing A (Inputs) for teesting
Start = 0
Size  = 2500
A = np.array(TestingData.drop('1', axis=1))[Start:Start+Size]

print('A Shape : ', A.shape)
print(A)

A Shape :  (2500, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
# Main / Finding K Nearest Neighbours and Predicting Label
Y_Predicted = np.zeros((A.shape[0], 1))
Y_Probability = []
rows = A.shape[0]
for j in range(0, rows):
  Distance = []

  m = X.shape[0]
  for i in range(0, m):
    Distance.append( np.sqrt(np.sum(( X[i] - A[j] )**2)) )

  TrainingData['Distance'] = Distance

  X_Sorted = np.array(TrainingData.sort_values(by = ['Distance']))

  k = 7
  K_Neighbours = np.array(X_Sorted[0:k, 0])

  count = []
  for i in range(0, 26):
    count.append(np.count_nonzero(K_Neighbours == (i+1)))

  max = 0
  for i in range(0,26):
    if count[i] > count[max]:
      max = i

  Y_Predicted[j] = max+1
  Y_Probability.append(str(round(count[max]*100/k)) + ' %')

In [8]:
# Output
print('EXPECTED vs PREDICTED')
print(np.concatenate((Y[Start:Start+Size], Y_Predicted, np.array([Y_Probability]).T), axis=1))

EXPECTED vs PREDICTED
[['1' '1.0' '100 %']
 ['1' '1.0' '86 %']
 ['1' '15.0' '57 %']
 ...
 ['4' '15.0' '86 %']
 ['4' '4.0' '100 %']
 ['4' '4.0' '86 %']]


In [9]:
# Calculating Accuracy
c = 0
for i in range(rows):
  if Y[Start+i] == Y_Predicted[i]:
    c+=1

print('Accuracy : ', (c/rows)*100, '%')

Accuracy :  86.88 %
