# ***LINEAR REGRESSION (Normal Equation)***

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd

## ***Training***

In [2]:
# Cost Function
def Cost(X, Y, theta):
  cost = (1/(2*(X.shape[0])))*(np.sum((np.dot(X, theta) - Y)**2))
  return cost

In [3]:
# Linear Regression Training Function Using Normal Equation
def LinearRegressionTraining(X, Y):
  theta = np.dot(np.dot(np.linalg.pinv(np.dot(X.T, X)), X.T), Y)
  return theta

In [4]:
# Function to Predict output
def Predict(X, theta):
  return np.dot(X, theta)

In [5]:
# Function to calculate RMSE
def RootMeanSquaredError(Y, Prediction):
  return (np.sum((Prediction-Y)**2))**(0.5)

In [6]:
# Importing Training Data 
TrainingData = pd.read_csv('drive/MyDrive/Colab Notebooks/Linear_train.csv')
TrainingData.pop('Unnamed: 0')
TrainingData

A            B          C          D          E            F  \
0      -9.989516  1564.957586   8.199060  32.508797  19.464400  1644.524093   
1     -17.591800  1559.053039  12.302737 -36.351098   6.256406  1640.834263   
2     -28.321695  1305.900952 -35.681049  -9.039358 -45.519426  2039.003363   
3     -40.471241  1612.746996 -28.980454   2.137719 -34.767491  2757.469393   
4     -36.525271  1852.275617 -32.744347  -1.439526 -14.061837  2138.422485   
...          ...          ...        ...        ...        ...          ...   
49995  38.882059  1829.766795  -9.597762  42.286077 -45.676532  2340.446842   
49996 -29.570690  1467.757407  -2.581269   8.699766 -32.209400  2065.685621   
49997 -26.656483  1081.812179  19.742925 -49.109287  -8.179490  1755.112415   
49998  49.470595  1418.823031  14.854524  -6.995360  27.184947  1235.231487   
49999 -25.982072  1679.672351 -34.735487 -16.517472   6.606794  2375.299327   

               G          H            I          J  ...           L  \
0      26.100966  34.731954  4378.575414 -14.151587  ...  770.535311   
1      12.954212 -43.333128  4833.766813  36.194771  ...  997.260070   
2      -0.154348  18.107957  4162.395297 -42.268523  ...  616.059291   
3      23.857472 -48.434183  4340.953927  35.960309  ...  715.537625   
4      44.061988  33.336936  4099.453685  28.212499  ...  629.221442   
...          ...        ...          ...        ...  ...         ...   
49995  44.758699 -49.232038  4561.096049   3.400968  ...  931.215587   
49996  13.244693 -27.154067  4922.613361  32.830061  ...  646.439398   
49997 -26.730046 -32.187078  4289.779346  30.641844  ...  950.109763   
49998  34.556613 -33.790945  4119.297411  36.747270  ...  742.735044   
49999  33.975192  -8.225393  4017.898569  22.664484  ...  888.777601   

               M          N          O          P          Q          R  \
0      30.060441 -25.002361  11.892468 -34.329383  37.218423  -4.440530   
1      -1.329145  16.022086  42.972484  -7.372877  45.550946  37.576551   
2      -6.997085  27.846844  26.511376  19.323152 -35.807513  -5.913019   
3     -12.441561  47.883435  36.994884  30.783992  22.162383  16.465836   
4      10.992360 -47.143335  -8.296962  -8.086565  39.169726 -49.540056   
...          ...        ...        ...        ...        ...        ...   
49995 -19.667192  20.825892  18.055764 -40.074521  44.966776  30.681416   
49996  45.407497 -41.574684 -41.278010  34.484129  16.631234 -10.488980   
49997  -1.341077 -33.268738  32.604813 -17.198521 -29.136001  24.609231   
49998 -48.406474  -4.081799  20.777856 -49.422060 -31.251860 -27.546928   
49999  33.897617 -25.710304  27.512513  29.199493  29.509718 -47.344110   

               S          T         label  
0      29.075092  29.107896    311.232491  
1      12.926551 -32.565844   6393.112342  
2      15.046779 -34.332357   2601.046223  
3      41.435425  33.561233  13572.118106  
4     -32.518653 -36.320202  -5462.446898  
...          ...        ...           ...  
49995  38.376682  33.942225   9034.945727  
49996 -11.637358 -25.774032  -6345.178110  
49997  11.935784 -35.190456   1483.917022  
49998  38.121308 -10.588040  10720.139180  
49999  -3.357583 -48.462504   2185.127958  

[50000 rows x 21 columns]

In [7]:
# Initializing X (Feature Values) for training
X = np.array(TrainingData.drop('label', axis=1))
X = np.concatenate((np.ones((X.shape[0],1)),X), axis=1)

print('X Shape : ', X.shape)
print(X)

X Shape :  (50000, 21)
[[ 1.00000000e+00 -9.98951633e+00  1.56495759e+03 ... -4.44053011e+00
   2.90750919e+01  2.91078961e+01]
 [ 1.00000000e+00 -1.75918001e+01  1.55905304e+03 ...  3.75765514e+01
   1.29265514e+01 -3.25658440e+01]
 [ 1.00000000e+00 -2.83216949e+01  1.30590095e+03 ... -5.91301909e+00
   1.50467787e+01 -3.43323575e+01]
 ...
 [ 1.00000000e+00 -2.66564827e+01  1.08181218e+03 ...  2.46092311e+01
   1.19357838e+01 -3.51904555e+01]
 [ 1.00000000e+00  4.94705951e+01  1.41882303e+03 ... -2.75469282e+01
   3.81213081e+01 -1.05880395e+01]
 [ 1.00000000e+00 -2.59820715e+01  1.67967235e+03 ... -4.73441099e+01
  -3.35758254e+00 -4.84625039e+01]]


In [8]:
# Initializing Y (Labels) for training
Y = np.array([TrainingData['label']]).T

print('Y Shape : ', Y.shape)
print(Y)

Y Shape :  (50000, 1)
[[  311.23249087]
 [ 6393.11234169]
 [ 2601.04622323]
 ...
 [ 1483.91702162]
 [10720.1391803 ]
 [ 2185.12795794]]


In [9]:
# Main / Determining theta (Coefficient) Values
theta = LinearRegressionTraining(X, Y)

print('theta Shape : ', theta.shape)
print(theta)

cost = Cost(X, Y, theta)
print('\nMinimized Cost : ', cost)

theta Shape :  (21, 1)
[[  0.41798009]
 [ 12.97514207]
 [  0.19986194]
 [-27.01640538]
 [  8.00839953]
 [ 37.01706628]
 [  0.15057057]
 [ 18.99806047]
 [-28.98788571]
 [  0.12003303]
 [ 22.99241979]
 [ 31.00883313]
 [  0.59855499]
 [-90.99824953]
 [ 34.00876787]
 [ 44.97847335]
 [ 51.01549757]
 [ 24.00743911]
 [ -1.00974707]
 [ 94.96623968]
 [ 25.00788367]]

Minimized Cost :  1907.0986737789892


In [10]:
# Predicting Training labels
Y_Predicted = np.dot(X, theta)

print('[[  EXPECTED    :    PREDICTED ]]')
print(np.concatenate((Y, Y_Predicted), axis=1))

print('\nRoot Mean Squared Error :', RootMeanSquaredError(Y, Y_Predicted))

[[  EXPECTED    :    PREDICTED ]]
[[  311.23249087   219.57758205]
 [ 6393.11234169  6349.85652898]
 [ 2601.04622323  2591.47498218]
 ...
 [ 1483.91702162  1481.12972159]
 [10720.1391803  10715.72943534]
 [ 2185.12795794  2186.58096826]]

Root Mean Squared Error : 13809.77434203394


## ***Testing***

In [11]:
# TESTING
# Importing Testing Data
TestingData = pd.read_csv('drive/MyDrive/Colab Notebooks/Linear_test.csv')
TestingData.pop('Unnamed: 0')
TestingData

A            B          C          D          E            F  \
0     40.790740  1187.897579 -28.941991  43.498302  14.157983  2536.000797   
1     47.968749  1498.588679  24.922821 -38.979082  16.405452  1798.950305   
2      9.762564  1316.354415   1.170771  10.365178 -11.993156  2714.382200   
3      6.414629  1895.586749  44.496934 -49.677800 -24.825833  2327.316373   
4     -4.112012  1130.920162  19.103960  -8.741503 -28.589701  1299.418975   
...         ...          ...        ...        ...        ...          ...   
9995 -37.802773  1204.712095  30.916166 -32.185868  -1.860028  1515.265232   
9996  21.841410  1067.350891  -9.598592  13.545191   2.910106  1286.431551   
9997 -34.734278  1630.673420  27.359399  -0.718695 -24.225154  1309.956055   
9998 -30.752354  1610.117693 -37.652326 -46.959112  18.151935  2489.587758   
9999  39.757972  1360.988948  -7.480509  27.155692  43.509194  1700.776478   

              G          H            I          J  ...           L  \
0    -34.181638 -14.940211  4746.739893 -25.100480  ...  707.727094   
1    -23.660484 -34.792328  4076.982013  16.042125  ...  737.135391   
2     26.382837  27.442924  4178.719984 -17.156579  ...  940.732329   
3      1.406644  44.103008  4586.697737 -10.834562  ...  925.441952   
4     42.946135   4.758032  4809.536369  42.375164  ...  797.953813   
...         ...        ...          ...        ...  ...         ...   
9995 -43.103776  12.911176  4865.716464 -28.856194  ...  877.773521   
9996 -49.542330  27.868152  4513.212740  46.710495  ...  518.544504   
9997  36.839488 -40.966273  4747.087919 -45.279378  ...  948.924788   
9998 -33.802220 -11.550250  4912.443446 -49.993634  ...  656.905027   
9999   4.496912  42.373176  4579.120167 -46.698784  ...  582.145397   

              M          N          O          P          Q          R  \
0     21.030812 -44.606156  -9.625546  42.276162 -11.000471 -19.830564   
1    -17.860346  42.274026 -19.886483  16.337922   9.025313  27.760845   
2    -35.879432  23.837924   3.729191  33.564390  12.848880 -45.837834   
3    -19.409771  25.346975  -7.729920 -42.813516 -17.666168  35.506064   
4    -46.788081  43.876292  34.009303  34.061089 -30.182903 -41.188733   
...         ...        ...        ...        ...        ...        ...   
9995 -14.401216  -1.152501   9.371124 -16.953167   5.590761  27.769178   
9996  -4.202304  -6.779170   2.384596  20.661830  -7.804846  -3.170458   
9997 -31.628023  -5.662373 -45.441406 -33.063193 -23.153715  -7.089845   
9998 -48.696117 -20.709813 -27.404294  14.174336  40.169075  37.329627   
9999  28.458183 -47.300191 -19.032777 -15.959350 -10.118301  38.306081   

              S          T         label  
0     -5.529430 -28.154864   -163.522723  
1     21.484409 -24.206545   6484.664510  
2    -49.592176  36.688611   2393.818082  
3    -49.048652 -34.048583  -9397.072355  
4     26.828040 -22.476663  10487.323575  
...         ...        ...           ...  
9995 -42.025878 -46.347044  -7526.092452  
9996  39.886812 -17.630468   6133.716734  
9997 -25.366712  47.034834  -1404.204034  
9998 -27.968720 -18.475040   1972.371711  
9999  -2.826688 -38.647683  -6120.248772  

[10000 rows x 21 columns]

In [12]:
# Initializing X_test
X_test = np.array(TestingData.drop('label', axis=1))
X_test = np.concatenate((np.ones((X_test.shape[0],1)),X_test), axis=1)

print('X_test shape : ', X_test.shape)
print(X)

X_test shape :  (10000, 21)
[[ 1.00000000e+00 -9.98951633e+00  1.56495759e+03 ... -4.44053011e+00
   2.90750919e+01  2.91078961e+01]
 [ 1.00000000e+00 -1.75918001e+01  1.55905304e+03 ...  3.75765514e+01
   1.29265514e+01 -3.25658440e+01]
 [ 1.00000000e+00 -2.83216949e+01  1.30590095e+03 ... -5.91301909e+00
   1.50467787e+01 -3.43323575e+01]
 ...
 [ 1.00000000e+00 -2.66564827e+01  1.08181218e+03 ...  2.46092311e+01
   1.19357838e+01 -3.51904555e+01]
 [ 1.00000000e+00  4.94705951e+01  1.41882303e+03 ... -2.75469282e+01
   3.81213081e+01 -1.05880395e+01]
 [ 1.00000000e+00 -2.59820715e+01  1.67967235e+03 ... -4.73441099e+01
  -3.35758254e+00 -4.84625039e+01]]


In [13]:
# Initializing Y_test
Y_test = np.array([TestingData['label']]).T

print('Y_test shape : ', Y_test.shape)
print(Y_test)

Y_test shape :  (10000, 1)
[[ -163.52272341]
 [ 6484.66451042]
 [ 2393.81808186]
 ...
 [-1404.204034  ]
 [ 1972.37171111]
 [-6120.24877236]]


In [14]:
# Predicting test labels
Y_test_Predicted = Predict(X_test, theta)

print('[[  EXPECTED    :    PREDICTED ]]')
print(np.concatenate((Y_test, Y_test_Predicted), axis=1))

print('\nRoot Mean Squared Error :', RootMeanSquaredError(Y_test, Y_test_Predicted))

[[  EXPECTED    :    PREDICTED ]]
[[ -163.52272341  -161.95570334]
 [ 6484.66451042  6482.49411349]
 [ 2393.81808186  2397.24820136]
 ...
 [-1404.204034   -1402.9354843 ]
 [ 1972.37171111  1976.02602503]
 [-6120.24877236 -6119.77479909]]

Root Mean Squared Error : 182.8687542001231


## ***Misc***

In [15]:
# Misc Example
Input = np.array([np.arange(1,10001)])
Input = Input.T
Output = 13*Input + 0.552
Input = np.concatenate((np.ones((Input.shape[0],1)), Input), axis=1)

print('Input shape : ', Input.shape)
print(Input)

print('\nOutput shape : ', Output.shape)
print(Output)

# Expected theta0 = 0.552
# Expected theta1 = 13
thetaNew = LinearRegressionTraining(Input, Output)
print('\nthetaNew Shape : ', thetaNew.shape)
print(thetaNew)

print('\nMinimized Cost : ', Cost(Input, Output, thetaNew))

Input shape :  (10000, 2)
[[1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00]
 [1.000e+00 3.000e+00]
 ...
 [1.000e+00 9.998e+03]
 [1.000e+00 9.999e+03]
 [1.000e+00 1.000e+04]]

Output shape :  (10000, 1)
[[1.35520000e+01]
 [2.65520000e+01]
 [3.95520000e+01]
 ...
 [1.29974552e+05]
 [1.29987552e+05]
 [1.30000552e+05]]

thetaNew Shape :  (2, 1)
[[ 0.5519997]
 [13.       ]]

Minimized Cost :  1.1085859406423735e-14
