In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Importing Training Data 
TrainingData = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/emnist-letters-train.csv")
TrainingData

23  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.406  0.407  \
0       7  0    0    0    0    0    0    0    0    0  ...      0      0   
1      16  0    0    0    0    0    0    0    0    0  ...      0      0   
2      15  0    0    0    0    0    0    0    0    0  ...      0      0   
3      23  0    0    0    0    0    0    0    0    0  ...      0      0   
4      17  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
88794   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88795  21  0    0    0    0    0    0    0    0    0  ...      0      0   
88796   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88797  23  0    0    0    0    0    0    0    0    0  ...      0      0   
88798  12  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.408  0.409  0.410  0.411  0.412  0.413  0.414  0.415  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
88794      0      0      0      0      0      0      0      0  
88795      0      0      0      0      0      0      0      0  
88796      0      0      0      0      0      0      0      0  
88797      0      0      0      0      0      0      0      0  
88798      0      0      0      0      0      0      0      0  

[88799 rows x 785 columns]

In [3]:
X = np.array(TrainingData.drop('23', axis=1))
print('X Shape : ', X.shape)
print(X)

X Shape :  (88799, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
Y = np.array([TrainingData['23']]).T
print('Y Shape : ', Y.shape)
print(Y)

Y Shape :  (88799, 1)
[[ 7]
 [16]
 [15]
 ...
 [ 1]
 [23]
 [12]]


In [5]:
# Importing Testing Data 
TestingData = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/emnist-letters-test.csv")
TestingData

1  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.548  0.549  \
0       1  0    0    0    0    0    0    0    0    0  ...      0      0   
1       1  0    0    0    0    0    0    0    0    0  ...      0      0   
2       1  0    0    0    0    0    0    0    0    0  ...      0      0   
3       1  0    0    0    0    0    0    0    0    0  ...      0      0   
4       1  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
14794  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14795  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14796  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14797  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14798  19  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.550  0.551  0.552  0.553  0.554  0.555  0.556  0.557  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
14794      0      0      0      0      0      0      0      0  
14795      0      0      0      0      0      0      0      0  
14796      0      0      0      0      0      0      0      0  
14797      0      0      0      0      0      0      0      0  
14798      0      0      0      0      0      0      0      0  

[14799 rows x 785 columns]

In [6]:
X_test = np.array(TestingData.drop('1', axis=1))
print('X_test Shape : ', X_test.shape)
print(X_test)

X_test Shape :  (14799, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
Y_test = np.array([TestingData['1']]).T
print('Y_test Shape : ', Y_test.shape)
print(Y_test)

Y_test Shape :  (14799, 1)
[[ 1]
 [ 1]
 [ 1]
 ...
 [19]
 [19]
 [19]]


In [8]:
class NeuralNetwork():
  def __init__(self, LayerSizes, Iterations, LearningRate):
    self.LayerSizes = LayerSizes
    self.Iterations = Iterations
    self.LearningRate = LearningRate
    self.Weights = self.Initialization()
    #self.Bias = np.ones(())
  
  def Initialization(self):
    InputLayer = self.LayerSizes[0]
    HiddenLayer1 = self.LayerSizes[1]
    HiddenLayer2 = self.LayerSizes[2]
    OutputLayer = self.LayerSizes[3]

    Parameters = {
        'W1' : np.zeros((HiddenLayer1, InputLayer)),
        'W2' : np.zeros((HiddenLayer2, HiddenLayer1)),
        'W3' : np.zeros((OutputLayer, HiddenLayer2))
    }

    return Parameters

  def Sigmoid(self, X):
    return 1/(1 + np.exp(-X))
  
  def d_Sigmoid(self, X):
    return (np.exp(-X))/((1 + np.exp(-X))**2)
  
  def SoftMax(self, X):
    exps = np.exp(X - X.max())
    return exps / np.sum(exps, axis=0)
  
  def d_SoftMax(self, X):
    exps = np.exp(X - X.max())
    return exps / np.sum(exps, axis=0) * (1 - exps / np.sum(exps, axis=0))
  
  def ForwardPropogation(self, X):
        Weights = self.Weights

        Weights['A0'] = X

        Weights['Z1'] = np.dot(Weights["W1"], Weights['A0'])
        Weights['A1'] = self.Sigmoid(Weights['Z1'])

        Weights['Z2'] = np.dot(Weights["W2"], Weights['A1'])
        Weights['A2'] = self.Sigmoid(Weights['Z2'])

        Weights['Z3'] = np.dot(Weights["W3"], Weights['A2'])
        Weights['A3'] = self.SoftMax(Weights['Z3'])

        return Weights['A3']
  
  def BackwardPropogation(self, Y, Output):
    Weights = self.Weights
    ChangeWeight = {}

    error = 2*(Output - Y) * self.d_SoftMax(Weights['Z3'])
    ChangeWeight['W3'] = np.outer(error, Weights['A2'])

    error = np.dot(Weights['W3'].T, error) * self.d_Sigmoid(Weights['Z2'])
    ChangeWeight['W2'] = np.outer(error, Weights['A1'])

    error = np.dot(Weights['W2'].T, error) * self.d_Sigmoid(Weights['Z1'])
    ChangeWeight['W1'] = np.outer(error, Weights['A0'])

    return ChangeWeight
  
  def UpdateWeights(self, ChangeWeight):
    for key, value in ChangeWeight.items():
      self.Weights[key] = self.Weights[key] - self.LearningRate * value

  def TestAccuracy(self, X_test, Y_test):
    Predictions = []

    for x,y in zip(X_test, Y_test):
      Output = self.ForwardPropogation(x.T)
      Predictions.append(Output == y)
    
    return np.mean(Predictions) * 100

  
  def Train(self, X, Y, X_test, Y_test):
    for i in range(self.Iterations):
      for x,y in zip(X, Y):
        Output = self.ForwardPropogation(x.T)
        ChangeWeight = self.BackwardPropogation(y, Output)
        self.UpdateWeights(ChangeWeight)
    
    Accuracy = self.TestAccuracy(X_test, Y_test)
    print('Accuracy : ', Accuracy)
      

In [9]:
LayerSizes = [784, 26, 26, 1]
Iterations = 1
LearningRate = 0.01

NN = NeuralNetwork(LayerSizes, Iterations, LearningRate)
NN.Train(X, Y, X_test, Y_test)

Accuracy :  5.399013446854517
